#!/usr/bin/env ruby
# encoding utf-8
=begin
Some description here
=end
require "rubygems" if RUBY_VERSION.include?("1.8")
require "dbus"
require "logger"
require "thread"
# ugly hack to handle symbolic links
require 'pathname'
APP_ROOT = File.dirname(Pathname.new(__FILE__).realpath)
require "#{APP_ROOT}/config"
Dir["#{APP_ROOT}/lib/*.rb"].each do |required|
  require "#{required}"
end

class Mpd2Kopete < SimpleDaemon::Base
  @m = MpdHandler.new

  def self.start
    @m.start
  end

  def self.stop
    @m.stop
  end
end

Mpd2Kopete.daemonize

#vim set ft=ruby
